# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='voted_posts',
            field=models.ManyToManyField(to='questions.Question', verbose_name='Voted questions'),
        ),
    ]
