language: python
python: 3.6
cache: pip

services:
- postgresql

before_install:
- pip install -r requirements-dev.txt

before_script:
- psql -c "CREATE USER $USER PASSWORD '$PASSWORD';" -U postgres
- psql -c "CREATE DATABASE $DB_NAME OWNER $USER;" -U postgres
- psql -c "ALTER USER $USER CREATEDB;" -U postgres
- python src/manage.py migrate

jobs:
  include:
  - stage: pre-commit tests
    script:
    - pre-commit run --all-files

  - stage: django tests
    script:
    - python src/manage.py test questions users
