version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: polls_db
    env_file:
      - src/main/.env
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  polls:
    build: .
    container_name: polls
    volumes:
      - .:/code
    env_file:
      - src/main/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: ./scripts/wait_for_it.sh

  redis:
    restart: always
    image: redis:3.2.0
    container_name: polls_cache
    expose:
      - "6379"
